---
# Kubernetes security hardening playbook

- name: Apply security hardening to Kubernetes nodes
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - vars/main.yml
  
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
  
  roles:
    - { role: common, tags: ['common', 'all'] }
    - { role: admin_user, tags: ['users', 'all'] }
    - { role: ssh_hardening, tags: ['ssh', 'all'] }
    - { role: firewall, tags: ['firewall', 'all'] }
    - { role: kernel_hardening, tags: ['kernel', 'all'] }
    - { role: audit, tags: ['audit', 'all'] }
    - { role: fail2ban, tags: ['fail2ban', 'all'] }
    - { role: containerd_security, tags: ['container', 'all'] }
    - { role: metrics_fix, tags: ['metrics', 'all'] }

  post_tasks:
    - name: Verify system status
      debug:
        msg: "Security hardening has been applied to {{ inventory_hostname }}" 