---
# Firewall role handlers

# This handler is kept for compatibility but may not be needed with the new approach
- name: Enable UFW
  ansible.builtin.shell: "{{ ufw_path.stdout | default('/usr/sbin/ufw') }} --force enable"
  changed_when: true
  when: ufw_path is defined and ufw_path.stdout != "" 