---
# Kernel hardening tasks

- name: Backup sysctl.conf
  copy:
    src: /etc/sysctl.conf
    dest: /root/security-backup/sysctl.conf.backup
    remote_src: true
    owner: root
    group: root
    mode: '0600'
  when: not ansible_check_mode

# Ensure the sysctl file exists before trying to modify it
- name: Ensure sysctl.d directory exists
  file:
    path: /etc/sysctl.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create initial sysctl configuration file
  file:
    path: /etc/sysctl.d/99-kubernetes-security.conf
    state: touch
    owner: root
    group: root
    mode: '0644'
  changed_when: false

- name: Set kernel parameters for security
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/99-kubernetes-security.conf
  with_items: "{{ sysctl_settings }}"

- name: Ensure the sysctl file has proper permissions
  file:
    path: /etc/sysctl.d/99-kubernetes-security.conf
    owner: root
    group: root
    mode: '0644'

- name: Apply sysctl settings
  command: sysctl --system
  changed_when: false
