---
# Firewall (UFW) configuration tasks

- name: Install UFW package
  apt:
    name: ufw
    state: present
    update_cache: yes
  register: ufw_install
  when: ansible_os_family == "Debian"

# Ensure UFW is available in the path after installation
- name: Ensure UFW is accessible in PATH
  block:
    - name: Check if UFW is installed correctly
      stat:
        path: /usr/sbin/ufw
      register: ufw_binary
      
    - name: Create UFW symlink if needed
      file:
        src: /usr/sbin/ufw
        dest: /usr/bin/ufw
        state: link
      when: ufw_binary.stat.exists
      
    - name: Refresh facts after installation
      setup:
        filter: ansible_path
  when: ufw_install is changed

- name: Set UFW default policies
  community.general.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
    state: enabled
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
  notify: Enable UFW

- name: Allow SSH access
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp
    comment: "SSH access"
  when: 
    - ufw_enabled
    - ufw_allow_ssh

- name: Configure UFW for Kubernetes API server
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
  with_items: "{{ ufw_kubernetes_ports }}"
  when: ufw_enabled

- name: Configure UFW for Cilium
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
  with_items: "{{ ufw_cilium_ports }}"
  when: ufw_enabled

- name: Enable UFW and apply rules
  ufw:
    state: enabled
    logging: on
  when: ufw_enabled
