---
# Fail2ban configuration tasks

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
    update_cache: yes
  when: 
    - fail2ban_enabled
    - ansible_os_family == "Debian"
  register: fail2ban_install

- name: Create fail2ban directory if it doesn't exist
  file:
    path: /etc/fail2ban
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: fail2ban_enabled

- name: Configure fail2ban
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban
  when: fail2ban_enabled

- name: Ensure fail2ban service is running and enabled
  service:
    name: fail2ban
    state: started
    enabled: yes
  when: fail2ban_enabled and not ansible_check_mode
  check_mode: false
