---
# Common role tasks

- name: Create backup directory
  file:
    path: "/root/security-backup"
    state: directory
    mode: '0700'
    owner: root
    group: root

- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-apt
      - sudo
      - acl
      - python3-pip
  when: ansible_os_family == "Debian"

- name: Set hostname information
  hostname:
    name: "{{ inventory_hostname }}"
  when: inventory_hostname is defined

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: "^{{ hostvars[item]['ansible_host'] }}\\s+{{ item }}\\s*.*$"
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
    state: present
  with_items: "{{ groups['all'] }}"
  when: hostvars[item]['ansible_host'] is defined

- name: Set timezone to UTC
  timezone:
    name: UTC

# Time synchronization - made optional via tags
- name: Time synchronization setup
  tags: 
    - time
    - ntp
  block:
    # Detect existing time services first
    - name: Gather service facts
      service_facts:
    
    - name: Check existing time synchronization
      debug:
        msg: >
          Detected time services:
          timesyncd {{ 'active' if ansible_facts.services['systemd-timesyncd.service'] is defined and 
                     ansible_facts.services['systemd-timesyncd.service'].state == 'running' else 'inactive' }}
    
    # Configure timesyncd if it's already active - preferred option
    - name: Configure systemd-timesyncd if active
      block:
        - name: Ensure timesyncd configuration directory exists
          file:
            path: /etc/systemd/timesyncd.conf.d
            state: directory
            mode: '0755'
            
        - name: Configure timesyncd NTP servers
          copy:
            dest: /etc/systemd/timesyncd.conf.d/ntp.conf
            content: |
              [Time]
              NTP=0.pool.ntp.org 1.pool.ntp.org 2.pool.ntp.org 3.pool.ntp.org
              FallbackNTP=ntp.ubuntu.com
            mode: '0644'
          notify: Restart timesyncd
      when: 
        - ansible_facts.services['systemd-timesyncd.service'] is defined 
        - ansible_facts.services['systemd-timesyncd.service'].state == 'running'
    
    # If no active time service, enable timesyncd as it's already available on most systems
    - name: Enable timesyncd if no time service is active
      block:
        - name: Ensure timesyncd is enabled and running
          service:
            name: systemd-timesyncd
            state: started
            enabled: yes
      when:
        - ansible_facts.services['systemd-timesyncd.service'] is defined
        - not ansible_check_mode
      check_mode: false

- name: Create security status file
  copy:
    dest: "/var/log/security-hardening.log"
    content: "Security hardening applied at {{ ansible_date_time.iso8601 }}\n"
    owner: root
    group: root
    mode: '0600'
