---
# Audit logging setup tasks

- name: Install auditd
  package:
    name: auditd
    state: present
  register: audit_install

- name: Backup existing audit rules
  copy:
    src: /etc/audit/rules.d/audit.rules
    dest: /etc/audit/rules.d/audit.rules.bak
    remote_src: true
  ignore_errors: true
  when: not ansible_check_mode

- name: Create audit rules directory
  file:
    path: /etc/audit/rules.d
    state: directory
    mode: '0750'
    owner: root
    group: root
  when: not ansible_check_mode or audit_install.changed

- name: Configure auditd settings
  template:
    src: auditd.conf.j2
    dest: /etc/audit/auditd.conf
    owner: root
    group: root
    mode: '0640'
  notify: restart auditd
  when: not ansible_check_mode or audit_install.changed

- name: Configure audit rules
  template:
    src: audit.rules.j2
    dest: /etc/audit/rules.d/audit.rules
    owner: root
    group: root
    mode: '0640'
  notify: restart auditd
  when: not ansible_check_mode or audit_install.changed

- name: Ensure auditd is running and enabled
  service:
    name: auditd
    state: started
    enabled: true
  when: not ansible_check_mode or audit_install.changed
